"""alter questions column

Revision ID: 26934c69f6e5
Revises: 616bf5b2aa6a
Create Date: 2025-04-02 13:58:02.317378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26934c69f6e5'
down_revision: Union[str, None] = '616bf5b2aa6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_question_question_id_fkey', 'category_question', type_='foreignkey')
    op.create_foreign_key(None, 'category_question', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subcategory_question_question_id_fkey', 'subcategory_question', type_='foreignkey')
    op.drop_constraint('subcategory_question_subcategory_id_fkey', 'subcategory_question', type_='foreignkey')
    op.create_foreign_key(None, 'subcategory_question', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subcategory_question', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategory_question', type_='foreignkey')
    op.drop_constraint(None, 'subcategory_question', type_='foreignkey')
    op.create_foreign_key('subcategory_question_subcategory_id_fkey', 'subcategory_question', 'subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key('subcategory_question_question_id_fkey', 'subcategory_question', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'category_question', type_='foreignkey')
    op.create_foreign_key('category_question_question_id_fkey', 'category_question', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
