"""alter questions column

Revision ID: 616bf5b2aa6a
Revises: 935e588b381a
Create Date: 2025-04-02 13:56:05.160779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616bf5b2aa6a'
down_revision: Union[str, None] = '935e588b381a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_question_category_id_fkey', 'category_question', type_='foreignkey')
    op.create_foreign_key(None, 'category_question', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_question', type_='foreignkey')
    op.create_foreign_key('category_question_category_id_fkey', 'category_question', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
