"""alter questions column

Revision ID: b5a4713f9dbe
Revises: d7a0fcecb12d
Create Date: 2025-04-02 15:41:10.407087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a4713f9dbe'
down_revision: Union[str, None] = 'd7a0fcecb12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_question_question_id_fkey', 'category_question', type_='foreignkey')
    op.drop_constraint('category_question_category_id_fkey', 'category_question', type_='foreignkey')
    op.create_foreign_key(None, 'category_question', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'category_question', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_question', type_='foreignkey')
    op.drop_constraint(None, 'category_question', type_='foreignkey')
    op.create_foreign_key('category_question_category_id_fkey', 'category_question', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('category_question_question_id_fkey', 'category_question', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
