"""alter questions column

Revision ID: cdfc7779ff2c
Revises: d988ca9e1848
Create Date: 2025-02-12 16:47:46.520192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfc7779ff2c'
down_revision: Union[str, None] = 'd988ca9e1848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('memo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'memo')
    # ### end Alembic commands ###
