"""alter questions column

Revision ID: d7a0fcecb12d
Revises: 26934c69f6e5
Create Date: 2025-04-02 15:38:05.037273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a0fcecb12d'
down_revision: Union[str, None] = '26934c69f6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_question_question_id_fkey', 'category_question', type_='foreignkey')
    op.drop_constraint('category_question_category_id_fkey', 'category_question', type_='foreignkey')
    op.create_foreign_key(None, 'category_question', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'category_question', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_question', type_='foreignkey')
    op.drop_constraint(None, 'category_question', type_='foreignkey')
    op.create_foreign_key('category_question_category_id_fkey', 'category_question', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('category_question_question_id_fkey', 'category_question', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
